"""Added populaiton column

Revision ID: da3b197b95cd
Revises: 
Create Date: 2020-10-11 22:55:44.566435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3b197b95cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kreise', sa.Column('population', sa.Integer(), nullable=True))
    op.alter_column('notifications', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('kreise', 'population')
    # ### end Alembic commands ###
